services:
  web:
    volumes:
      - ./:/usr/share/nginx/html/
    image: nginx
  python:
    image: krajewskim/python-api:new
    ports:
      - 5002:5002
    depends_on: 
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis