apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-counter
  labels:
    projekt: python
  annotations:
    purpose: "cronjob that automatically increases python counter"
spec:
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        projekt: python 
    spec:
      template:
        metadata:
          labels:
            projekt: python
        spec:
          containers:
          - name: counter
            image: cmd.cat/curl
            command:
            - curl
            - -XPOST
            - python-service/api/v1/info
          restartPolicy: Never
