apiVersion: v1
kind: Pod
metadata:
  name: python-api
  labels:
    name: python-api
spec:
  containers:
  - name: python-api
    image: krajewskim/python-api:new
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5002
  
    